default:
  log:
    level: info
  short_env: default

development:
  log:
    level: debug
  short_env: dev

empty_env:

staging:
  short_env: stg

production:
  short_env: prd
  log:
    level: error
